/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f030x8.h"

//#define LED_PIN 5
#define BTN_SAMPL_TIME 5


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint32_t Tick;

//casovanie cez SysTick

void SysTick_Handler(void)
{
	Tick++;
}


void blikac(void)
{
	static uint32_t delay;
	static uint32_t LED_TIME_BLINK = 300;


	if (Tick > delay + LED_TIME_BLINK) {
		GPIOA->ODR ^=(1<<4);
		delay = Tick;
	}
}

//Obsluha(handler), ktora sa stara o prerusenia
void EXTI0_1_IRQHandler(void)
{
	if (EXTI->PR & EXTI_PR_PR0) { // check line 0 has triggered the IT
		EXTI->PR |= EXTI_PR_PR0; // clear the pending bit
		GPIOB->ODR ^= GPIO_ODR_0;
	}
}

//blikanie
void blikatko(void)
{
	static enum { LED_OFF, LED_ON } stav;
	static uint32_t DelayCnt = 0;

	if (stav == LED_ON) {
		if (Tick > (DelayCnt + 300)) {
			GPIOD->BRR = (1<<0);
			DelayCnt = Tick;
			stav = LED_OFF;
		}
	}
}



void tlacitka(void)
{
	//S2
	static uint32_t old_s2;
	uint32_t new_s2 = GPIOC->IDR & (1<<0);
	static uint32_t off_time;
	static uint32_t LED_TIME_SHORT = 100;

	// S1
	static uint32_t old_s1;
	uint32_t new_s1 = GPIOC->IDR & (1<<1);
	static uint32_t LED_TIME_LONG = 1000;

	// S2
	if (old_s2 && !new_s2) { // falling edge
		off_time = Tick + LED_TIME_SHORT;
		GPIOB->BSRR = (1<<0);
	}
	old_s2 = new_s2;

	if (Tick > off_time) {
		GPIOB->BRR = (1<<0);
	}

	//S1
	if (old_s1 && !new_s1) { // falling edge
		off_time = Tick + LED_TIME_LONG;
		GPIOB->BSRR = (1<<0);
	}
	old_s1 = new_s1;

	if (Tick > off_time) {
		GPIOB->BRR = (1<<0);
	}
}

void tlacitka2()
{
	static uint32_t old_s2;
	uint32_t new_s2 = GPIOC->IDR & (1<<0);
	static uint32_t LED_TIME_SHORT = 100;

	static uint32_t old_s1;
	uint32_t new_s1 = GPIOC->IDR & (1<<1);
	static uint32_t LED_TIME_LONG = 1000;

	static uint32_t off_time;


	static uint16_t delay_5 = 5;
	static uint16_t delay_40 = 40;

	// S2
	if (old_s2 && !new_s2) { // falling edge
		off_time = Tick + LED_TIME_SHORT;
		GPIOB->BSRR = (1<<0);
	}
	old_s2 = new_s2;

	if (Tick > off_time + delay_40)
	{
		GPIOB->BRR = (1<<0);
	}

	//S1
	if (GPIOC->IDR & (1<<1))
	{
		static uint16_t debounce = 0xFFFF;
		debounce <<= 1;
		if (new_s1) debounce |= 0x0001;

		if (old_s1 && !new_s1) { // falling edge
			off_time = Tick + LED_TIME_LONG;
			GPIOB->BSRR = (1<<0);
		}
		old_s1 = new_s1;

		if (Tick > off_time + delay_5) {
			GPIOB->BRR = (1<<0);
		}
	}
}


void tlacitka3(void){
	static uint16_t debounce = 0xFFFF;
	static uint32_t off_time = 0;
	static uint32_t delay = 0;
	static uint32_t LED_TIME_SHORT = 100;
//	static uint32_t LED_TIME_LONG = 1000;

	if (Tick > delay + BTN_SAMPL_TIME){
		delay = Tick;

		debounce <<=1;
		if (GPIOC->IDR & (1<<0)) debounce |= 0x001;
		if (debounce == 0x8000) {
			off_time = Tick + LED_TIME_SHORT;
			GPIOB->BSRR = (1<<0);
		}
	}

	if (Tick > off_time){
		GPIOB->BSRR = (1<<0);
	}
}




int main(void)
{

	GPIOA->MODER |= GPIO_MODER_MODER5_0;   //MODER - register
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN;   //(zapis vyberu do registru)  setting clock
	GPIOA->MODER |= GPIO_MODER_MODER4_0;  // LED1 = PA4, output
	GPIOB->MODER |= GPIO_MODER_MODER0_0; // LED2 = PB0, output
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_1; // S1 = PC1, pullup

	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN; 	//clock urceny pre interrupty

	//vyber zdroju prerusenia, povolenie masky a zvolenie aktivnej hrany
	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PC; // select PC0 for EXTI0
	EXTI->IMR |= EXTI_IMR_MR0; // mask
	EXTI->FTSR |= EXTI_FTSR_TR0; // trigger on falling edge
	//NVIC_EnableIRQ(EXTI0_1_IRQn); // enable EXTI0_1

	SysTick_Config(8000); // 1ms

	while (1){
		blikatko();
		//tlacitka();
		//tlacitka2();
		tlacitka3();
	}

}
